# Generated by Django 4.0.6 on 2022-07-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='category',
        ),
        migrations.AddField(
            model_name='tile',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='numberofbathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='numberofbedroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
